/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Adder_LogEntry */

#ifndef _Included_Adder_LogEntry
#define _Included_Adder_LogEntry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
